<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ppr">
    <xacro:property name="PI" value="3.14159265358979"/>
    <xacro:property name="mass" value="1"/>
    <xacro:property name="width1" value="1"/>
    <xacro:property name="width2" value="0.1"/>
    <xacro:property name="height1" value="0.1"/>
    <xacro:property name="height2" value="1"/>
    <xacro:property name="height3" value="1"/>
    <xacro:property name="height4" value="0.1"/>
    <xacro:property name="camera_link" value="0.05"/>
    <xacro:property name="axel_offset" value="0.05"/>
    
    <xacro:include filename="$(find ppr_description)/urdf/ppr.gazebo"/>
    
    <xacro:include filename="$(find ppr_description)/urdf/materials.xacro"/>
    
    <!-- <link name="world"/>
    
    <joint name="fixed" type="fixed">
        <parent link="world"/>
        <child link="link1"/>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint> -->
    
    <link name="link1">
        <collision>
            <origin xyz="0 0 ${height1/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${width1}" length="${height1}"/>
            </geometry>
        </collision>>
        <visual>
            <origin xyz="0.0 0.0 ${height1/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${width1}" length="${height1}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <inertial>
            <origin xyz="0.0 0.0 ${height1/2}" rpy="0.0 0.0 0.0"/>
            <mass value="${mass}"/>
            <inertia 
            ixx="${mass / 12.0 * (width1*width1 + height1*height1)}" ixy="0.0" ixz="0.0" 
            iyy="${mass / 12.0 * (height1*height1 + width1*width1)}" iyz="0.0" 
            izz="${mass / 12.0 * (width1*width1 + width1*width1)}"/>
        </inertial>
    </link>

    <joint name="motor1" type="revolute">
        <parent link="link1"/>
        <child link="link1_1"/>
        <axis xyz="1 0 0"/>
        <limit lower="-3.14159" upper="3.14159" velocity="50.0" effort="1000.0"/>
        <origin xyz="${0.866025404*width1} ${0.5*width1} ${height1 - axel_offset}" rpy="0 0 ${pi*2/3}"/>
        <dynamics damping="0.7" friction="0.0"/>        
    </joint>

    <link name="link1_1">
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.001" length="0.001"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.001" length="0.001"/>
            </geometry>
            <material name="black"/>
        </visual>
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="${mass}"/>
            <inertia 
            ixx="${mass / 12.0 * (width2*width2 + height2*height2)}" ixy="0.0" ixz="0.0" 
            iyy="${mass / 12.0 * (height2*height2 + width2*width2)}" iyz="0.0" 
            izz="${mass / 12.0 * (width2*width2 + width2*width2)}"/>
        </inertial>
    </link>
    
    

    <joint name="motor2" type="prismatic">
        <parent link="link1_1"/>
        <child link="link2"/>
        <axis xyz="0 0 1"/>
        <limit lower="0.0" upper="${height2}" effort="1000.0" velocity="0.5"/>        
        <!-- <origin xyz="${0.866025404*width1} ${0.5*width1} ${height1 - axel_offset}" rpy="0 0 0"/> -->
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>        
        <dynamics damping="0.7" friction="0.0"/>
    </joint>
        
    <link name="link2">
        <collision>
            <origin xyz="0.0 0.0 ${height2/2 - axel_offset}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${width2}" length="${height2}"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0.0 0.0 ${height2/2 - axel_offset}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${width2}" length="${height2}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <inertial>
            <origin xyz="0.0 0.0 ${height2/2}" rpy="0.0 0.0 0.0"/>
            <mass value="${mass}"/>
            <inertia 
            ixx="${mass / 12.0 * (width2*width2 + height2*height2)}" ixy="0.0" ixz="0.0" 
            iyy="${mass / 12.0 * (height2*height2 + width2*width2)}" iyz="0.0" 
            izz="${mass / 12.0 * (width2*width2 + width2*width2)}"/>
        </inertial>
    </link>

    <joint name="motor4" type="revolute">
        <parent link="link2"/>
        <child link="upper_link"/>
        <limit lower="-3.14" upper="3.14" effort="100.0" velocity="1.7"/>        
        <origin xyz="0 0 ${height2}" rpy="0.0 0.0 0"/>
        <axis xyz="1 0 0"/>
    </joint>

    <link name="upper_link">
         <collision>
            <origin xyz="0 ${width1} 0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${width1}" length="${height1}"/>
            </geometry>
        </collision>>
        <visual>
            <origin xyz="0 ${width1} 0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${width1}" length="${height1}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <inertial>
            <origin xyz="0 ${width1} 0" rpy="0.0 0.0 0.0"/>
            <mass value="${mass}"/>
            <inertia 
            ixx="${mass / 12.0 * (width1*width1 + height1*height1)}" ixy="0.0" ixz="0.0" 
            iyy="${mass / 12.0 * (height1*height1 + width1*width1)}" iyz="0.0" 
            izz="${mass / 12.0 * (width1*width1 + width1*width1)}"/>
        </inertial>
    </link>



     <joint name="motor3" type="prismatic">
        <parent link="link1"/>
        <child link="link4"/>
        <axis xyz="0 0 1"/>
        <limit lower="0.0" upper="1" velocity="0.5" effort="1000.0"/>
        <origin xyz="${0.866025404*-width1} ${-0.5*width1} ${height1 - axel_offset}" rpy="0 0 0"/>
        <dynamics damping="0.7" friction="0.0"/>
        
    </joint>
    <link name="link4">
        
    </link>


    <!-- <link name="link3">
        <collision>
            <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${width2}" length="${height3}"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0.0 0.0 ${height3/2 - axel_offset}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${width2}" length="${height3}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <inertial>
            <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
            <mass value="${mass}"/>
            <inertia
            ixx="${mass / 12.0 * (width2*width2 + height3*height3)}" ixy="0.0" ixz="0.0"
            iyy="${mass / 12.0 * (height3*height3 + width2*width2)}" iyz="0.0"
            izz="${mass / 12.0 * (width2*width2 + width2*width2)}"/>
        </inertial>
    </link> -->
<!--
    <joint name="motor4" type="prismatic">
        <parent link="link3"/>
        <child link="link3_1"/>
        <axis xyz="0 1 0"/>
        <limit lower="0" upper="1" velocity="50.0" effort="1000.0"/>
        <origin xyz="0 0 ${height3 - axel_offset/2}" rpy="0 0 0"/>
        <dynamics damping="0.7" friction="0.0"/>        
    </joint>
    <link name="link3_1">
        
    </link> -->
    <!-- <link name="link3_1">
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.1" length="1"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.1" length="0.1"/>
            </geometry>
            <material name="black"/>
        </visual>
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="${mass}"/>
            <inertia 
            ixx="${mass / 12.0 * (width2*width2 + height2*height2)}" ixy="0.0" ixz="0.0" 
            iyy="${mass / 12.0 * (height2*height2 + width2*width2)}" iyz="0.0" 
            izz="${mass / 12.0 * (width2*width2 + width2*width2)}"/>
        </inertial>
    </link> -->
<!-- 
    <joint name="hokuyo_joint" type="fixed">
        <parent link="link3"/>
        <child link="hokuyo_link"/>
        <origin xyz="0.0 0.0 ${height3 - axel_offset/2}" rpy="0.0 0.0 0.0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="hokuyo_link">
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <inertial>
            <mass value="1e-5" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
        </inertial>
    </link>
    
    <joint name="camera_joint" type="fixed">
        <parent link="link3"/>
        <child link="camera_link"/>
        <origin xyz="${camera_link} 0.0 ${height3 - axel_offset*2}" rpy="0.0 0.0 0.0"/>
        <axis xyz="0.0 1 0.0"/>
    </joint>
    
    <link name="camera_link">
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${camera_link} ${camera_link} ${camera_link}"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${camera_link} ${camera_link} ${camera_link}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <inertial>
            <mass value="1e-5" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
        </inertial>
    </link>
    
    <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_link_optical"/>
        <origin xyz="0.0 0.0 0.0" rpy="${-pi/2} 0.0 ${-pi/2}"/>
    </joint>
    
    <link name="camera_link_optical"/> -->


    



    <transmission name="tran1">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="motor1">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor1">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="tran2">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="motor2">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor2">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="tran3">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="upper_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor3">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

</robot>