arm_group_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - arm_shoulder_pan_joint
     - arm_shoulder_lift_joint
     - arm_elbow_joint
     - arm_wrist_1_joint
     - arm_wrist_2_joint
     - arm_wrist_3_joint

  gains:
    arm_shoulder_pan_joint: {p: 10.0, i: 0.0, d: 0.0}
    arm_shoulder_lift_joint: {p: 10.0, i: 0.0, d: 0.0}
    arm_elbow_joint: {p: 10.0, i: 0.0, d: 0.0}
    arm_wrist_1_joint: {p: 10.0, i: 0.0, d: 0.0}
    arm_wrist_2_joint: {p: 10.0, i: 0.0, d: 0.0}
    arm_wrist_3_joint: {p: 10.0, i: 0.0, d: 0.0}

  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      arm_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      arm_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      arm_elbow_joint: {trajectory: 0.1, goal: 0.1}
      arm_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      arm_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      arm_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  
arm_joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
     - arm_shoulder_pan_joint
     - arm_shoulder_lift_joint
     - arm_elbow_joint
     - arm_wrist_1_joint
     - arm_wrist_2_joint
     - arm_wrist_3_joint

