parabot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: motor1
    pid: {p: 8000.0, i: 0.0, d: 50.0}
  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: motor2
    pid: {p: 8000.0, i: 0.0, d: 50.0}
  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: motor3
    pid: {p: 8000.0, i: 0.0, d: 50.0}