parabot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: parabot::motor1
    pid: {p: 5000.0, i: 0.0, d: 20.0}
  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: parabot::motor2
    pid: {p: 5000.0, i: 0.0, d: 20.0}
  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: parabot::motor3
    pid: {p: 5000.0, i: 0.0, d: 20.0}